spring:
  # ??Spring Boot??????Web???????????
  main:
    web-application-type: none
  config:
    # ?????????????http://localhost:8888?????????
    import: "configserver:http://localhost:8888"
  application:
    # ???????Git?????????(hy2-installer.yml)???????
    # ???????????????????
    name: hy2-installer
